### ISSUE TITLE
The explain-results function does not work with 1.10-alpha*

### ISSUE THREAD

**Issue by arichiardi** [bhb/expound#124] opened 2018-09-18 23:26 UTC
Hi again :smile: 

I have just discovered (in ClojureScript) that the `explain-results` function does not work if I have the `1.10-alpha6` dependency in.

Instead of printing the nicely formatted spec failure it prints something like:

```clojure
 threw error

#error {:message "Call to #'my-ns/my-fn did not conform to spec:...
```

Moving back to `1.9.0` solved the problem.

:+1:

**Comment by arichiardi** [comment] 2018-09-18 23:35
Uhm this seems not to be true, I got the `#error` record again after some time. Cannot understand why.

**Comment by bhb** [comment] 2018-09-19 00:11
@arichiardi I've seen some strange results with `1.10-alpha6` myself, depending on whether I'm using `lein` or `clj` (Alex Miller noted some REPLs may need to be updated to take advantage of changes in error reporting in 1.10, although I'm not 100% clear on details). If possible, can you try `1.10-alpha8`? I may be imagining things, but I think that has resolved the issue I saw.

I'm sure the issues *are* reproducible, but frankly there are so many moving parts (new `clj`, `clj` vs `lein` vs `boot`, new `spec.alpha`, new Clojure version) that I'm going to let the dust settle a bit before I update Expound. That said, if you see bugs with the latest of the above,

**Comment by arichiardi** [comment] 2018-09-19 00:15
Trying now :wink:

**Comment by arichiardi** [comment] 2018-09-19 00:41
It looks like `1.10.0-alpha8` takes orders of magnitude more time to generate my tests. So much that I cannot wait to complete to see what happens :smile: 

```
[:gen-test] Build completed. (110 files, 1 compiled, 0 warnings, 20.08s)
Generative testing started...
```

I think this is not stable enough though, will fiddle with it a bit later :wink: Thanks for answering though!

**Comment by bhb** [comment] 2018-12-13 02:14
@arichiardi I'm going to close this for now, but please let me know if you see any issues with 1.10.0 and Expound (you may want to try 0.7.2-SNAPSHOT, since I will hopefully release that soon). Thanks!

**Closed by bhb** 2018-12-13 02:14 UTC

**Comment by arichiardi** [comment] 2018-12-13 05:58
Yep no problem, haven't noticed it anymore so maybe it magically disappeared. Thank you!
