### ISSUE TITLE
Instructions cause runtime error

### ISSUE THREAD

**Issue by devth** [bhb/expound#19] opened 2017-08-21 18:18 UTC
Why do the docs suggest:

```clojure
;; Or set it globally
(set! s/*explain-out* expound/printer)
```
?

This results in a runtime error:

```
Caused by: java.lang.IllegalStateException: Can't change/establish root binding of: *explain-out* with set
```

> Currently, it is an error to attempt to set the root binding of a var using set!, i.e. var assignments are thread-local.

https://clojure.org/reference/vars#set

**Comment by bhb** [comment] 2017-08-23 00:49
Thanks for reporting this! What version of Clojure and `clojure.spec` are you using?

**Comment by bhb** [comment] 2017-08-23 01:03
Are you running this at the REPL or in some other way?

**Comment by devth** [comment] 2017-08-23 01:07
1.9.0-alpha17. Strangely, it works in tests and in the REPL but fails when run from a `-main` inside an Uberjar.

**Comment by bhb** [comment] 2017-08-23 01:12
Thanks for the info! The following works

1. `lein new expound-client-command-line`
2. Add `:main expound-client-command-line.core` to project.clj
3. Edit `src/expound_client_command_line/core.clj` to be

```clojure
(ns expound-client-command-line.core
  (:require [clojure.spec.alpha :as s]
            [expound.alpha :as expound]))

(s/def ::name string?)

(defn -main []
  (set! s/*explain-out* expound/printer)
  (s/explain ::name 1))
```

I will see if I can reproduce with an uberjar.

**Comment by bhb** [comment] 2017-08-23 01:36
@devth I can reproduce with an uberjar. Unfortunately, I've been looking for a concise explanation of why this won't work with an uberjar and I haven't found anything yet, but my googling may be failing me. I'd be happy to add a note to the instructions, but I'd like to have a link or at least an explanation.

Can you talk more about your use case? In most cases, I would not expect the final uberjar artifact to be using expound (it's generally a dev-time library). I suppose one could use expound to, say, display error messages for an API, but in this case, would using `binding` be sufficient to localize the effect of changing `*explain-out*`?

**Comment by devth** [comment] 2017-08-23 03:06
@bhb thanks. I was partly trying to figure out why `set!` didn't work and whether I was just missing something. The docs weren't super clear, and now they're all the more confusing.

Keeping it in an uberjar was for convenience and we would have removed it eventually. I'll remove it now instead. And yes, binding would be perfectly usable in an uberjar since there's a natural entrypoint to bind from.

**Comment by athos** [comment] 2017-08-24 01:31
Dynamic vars have to be bound with `binding` before you `set!` values to them.
But, in most cases you don't have to do it yourself in the REPL for dynamic vars defined in Clojure core because Clojure REPL does that for you before getting started (cf. https://github.com/clojure/clojure/blob/master/src/clj/clojure/main.clj#L71-L89).

In this case, I think something like the following should work:

```clj
(binding [s/*explain-out* expound/printer]
  (s/explain ::name 1))
```

Note that this might not work if the body of the `binding` form would be executed in other thread.

**Comment by bhb** [comment] 2017-08-24 02:41
@athos Ah, thank you for the explanation! This all makes more sense now.

@devth Thanks again for reporting this. I certainly did not understand all the subtleties of using `set!`. But since `set!` works in the contexts that I would expect clients to use Expound (namely, at dev time), I'm leaning towards leaving the documentation as-is for now. If this continues to be a source of confusion, I'll reconsider modifying the documentation to either only recommend using `binding` or adding a note about when `set!` won't work.

**Comment by aisamu** [comment] 2018-10-16 14:39
We just got bitten by that as well, might be useful to point it out in the docs!
We're using it in dev and testing only - but we use tomcat during testing, so our artifact is an uberjar.

Would `alter-var-root` be a valid alternative? It looks like Pallet used it at some point: 
(From https://stackoverflow.com/a/16448108/7182237, pasting for convenience)
 ```
(defn force-slf4j
  "The repl task brings in commons-logging, which messes up our logging
   configuration. This is an attempt to restore sanity."
   []
  (binding [*ns* (the-ns 'clojure.tools.logging.slf4j)]
    (alter-var-root
     #'clojure.tools.logging/*logger-factory*
     (constantly (clojure.tools.logging.slf4j/load-factory)))))
```

**Comment by aisamu** [comment] 2018-10-17 12:38
> Unfortunately, alter-var-root doesn't always work either

Oh, :(
At least the failure mode is not so bad (set! throws an exception and halts tomcat), and if I'm in a REPL I imagine I can rebind it myself. 

To be fair, I went straight to the orchestra section and completely missed this paragraph. Even now, knowing it was there, I still had a bit of trouble finding it.

It might be the case that the title could have been more elaborate (e.g. just like "Using orchestra", we could have "Using expound as the default printer for clojure.spec/orchestra"), or perhaps we need a reference on the orchestra section (e.g. "The same binding restrictions apply (*explain-out* link)").

> I think it's good to mention both alter-var-root and set! and discuss when they are appropriate (and probably default to set!, since it's appropriate for most use cases).

I agree that it might be useful to have them described in more detail - either with a more explicit section or with comments in the code snippets.

Thanks for both the quick response and this glorious lib!

**Comment by bhb** [comment] 2018-10-17 22:16
> (e.g. "The same binding restrictions apply (explain-out link)")

Good idea! I'll leave this open as a doc issue - I may also explore whether I can just figure out an API that doesn't require users dive into the details of `set!` and `alter-var-root` entirely by intelligently installing Expound. We'll see.

**Comment by bhb** [comment] 2018-12-15 02:39
Closing with https://github.com/bhb/expound/pull/142

**Closed by bhb** 2018-12-15 02:39 UTC
Labels: bug
