### ISSUE TITLE
Expound providing clojurescript?

### ISSUE THREAD

**Issue by olivergeorge** [bhb/expound#16] opened 2017-08-16 00:53 UTC
Something in the expound's configuration causes Cursive to have trouble resolving functions cleanly.  I'm not sure why this happens.

![image](https://user-images.githubusercontent.com/99447/29342931-1d1c0936-8271-11e7-8d1d-2c1d8ab3d524.png)

**Comment by bhb** [comment] 2017-08-16 01:36
Thanks for reporting this! 

It looks like it's a known [Cursive bug](https://github.com/cursive-ide/cursive/issues/1132) but it does not appear to happen with all `.cljc` files (for instance, I could not reproduce it with [Integrant](https://github.com/weavejester/integrant)). 

I'll look into this more. If there is something I can change in the `project.clj` file that fixes this without breaking other scenarios, I'm happy to try it.

**Comment by danielcompton** [comment] 2017-08-16 01:37
<img width="619" alt="screenshot of finder 16-08-17 1-37-03 pm" src="https://user-images.githubusercontent.com/811954/29343870-08bd6d10-8288-11e7-98fa-800918fcf435.png">

I think this is because the jar includes compiled files in it? https://repo.clojars.org/expound/expound/

**Comment by bhb** [comment] 2017-08-16 02:04
@danielcompton Thanks very much for the idea! That does indeed look suspicious. I'll look into how to exclude this directory when doing `lein deploy clojars`

**Comment by danielcompton** [comment] 2017-08-16 02:09
Because they are in `resources/public` this would be included by default. You can use [`:jar-exclusions`](https://github.com/technomancy/leiningen/blob/b34d226f56e11bb11d2b3e089cb8b618e88d3c53/sample.project.clj#L408), or maybe compile the CLJS into a different directory?

**Comment by bhb** [comment] 2017-08-16 02:14
@danielcompton Hm, I'm considering my options here. I put everything in `resources` originally so that I could connect to Figwheel in the browser to access a CLJS REPL, but it does seem cleaner to compile all CLJS for tests in, say `target`.

OTOH, just using `:jar-exclusions` would fix this for now, even if it's a bit of a hacky workaround

**Comment by bhb** [comment] 2017-08-16 02:30
@danielcompton I can confirm that excluding these files from the jar fixes the issue. Thanks **very** much for the idea, that would not have occurred to me!

I'll weigh my options and figure out a good fix for this ASAP.

**Comment by bhb** [comment] 2017-08-16 03:10
@olivergeorge OK, I think I've got a simple fix for this. I think eventually I'll take @danielcompton's suggestion to reconfigure the project to not put compiled JS in `resources`, but for now, I've updated the `:clean-targets` option in `project.clj`.

Would you mind confirming the fix?

1. `git clone git@github.com:bhb/expound.git`
1. `cd expound`
1. `git checkout cursive-bug`
1. `lein install`
2. In your test project, include `[expound "0.2.1-SNAPSHOT"]`

**Comment by olivergeorge** [comment] 2017-08-16 03:20
@bhb Confirmed.  0.2.1-SNAPSHOT resolves the problem.

**Comment by bhb** [comment] 2017-08-16 14:09
@olivergeorge Thanks for testing!

**Closed** 2017-08-16 14:10 UTC

**Comment by bhb** [comment] 2017-08-16 14:16
I've released 0.2.1 to address this.
